Feature/sign in/sign up
peaksoft-school/js6-bilingual pull request #52
Opened 2022-11-10 10:16 UTC by emirlanjumaev

2022-11-14 10:40 UTC, songhee24 requested changes

2022-11-14 10:40 UTC, songhee24 commented on src/containers/SignIn.jsx
>  const SignIn = () => {
![Screen Shot 2022-11-14 at 16 33 35](https://user-images.githubusercontent.com/44497623/201638335-1f115102-3438-49e2-b9c7-58cdc8784ab2.png)

![Screen Shot 2022-11-14 at 16 33 45](https://user-images.githubusercontent.com/44497623/201638368-1662855b-932c-4482-a1ad-180af377c851.png)

Мне кажется или размеры немного не правильные 
Почему они меняются когда я переключаю их ?

2022-11-14 10:40 UTC, songhee24 commented on src/containers/SignIn.jsx
>  const SignIn = () => {
Вообще можно было бы все это сделать одной компонентой не обязательно две компоненты создавать

2022-11-14 10:40 UTC, songhee24 commented on src/containers/SignIn.jsx
> +            console.log(error);
ошибки нужно отображать пользователю

2022-11-14 10:40 UTC, songhee24 commented on src/containers/SignUp.jsx
> +            console.log(error);
тоже самое здесь

2022-11-14 10:40 UTC, songhee24 commented on src/utils/constants/api.js
> +/// ///////////////////////////////////////////////////////////////////////////////
такие комментарий не надо оставлять

2022-11-14 12:40 UTC, emirlanjumaev commented on src/containers/SignIn.jsx
>  const SignIn = () => {
#Fixed

2022-11-15 04:07 UTC, songhee24 requested changes

2022-11-15 04:07 UTC, songhee24 commented on src/containers/SignIn.jsx
> +                                <span> Incorrect email and/or password </span>
Incorrect email and/or password это не правильно ошибки полностью должны приходить из бэкенда

2022-11-15 04:07 UTC, songhee24 commented on src/containers/SignUp.jsx
> +                                <span> This account already exists </span>
здесь тоже самое

2022-11-15 04:07 UTC, songhee24 commented on src/containers/SignUp.jsx
> +                                <span> This account already exists </span>
если бэкенд не показывает ошибки значит ты должен им сказать нормальные ошибки скидывать или хотя бы типы ошибок

2022-11-17 07:33 UTC, merged